<?php
/**
 * InfoTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Semux\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Semux API
 *
 * Semux is an experimental high-performance blockchain platform that powers decentralized application.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Semux\Client;

/**
 * InfoTypeTest Class Doc Comment
 *
 * @category Class 
*/
// * @description InfoType
/**
 * @package     Semux\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InfoTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InfoType"
     */
    public function testInfoType()
    {
    }

    /**
     * Test attribute "clientId"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "coinbase"
     */
    public function testPropertyCoinbase()
    {
    }

    /**
     * Test attribute "latestBlockNumber"
     */
    public function testPropertyLatestBlockNumber()
    {
    }

    /**
     * Test attribute "latestBlockHash"
     */
    public function testPropertyLatestBlockHash()
    {
    }

    /**
     * Test attribute "activePeers"
     */
    public function testPropertyActivePeers()
    {
    }

    /**
     * Test attribute "pendingTransactions"
     */
    public function testPropertyPendingTransactions()
    {
    }
}
