<?php
/**
 * PeerTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Semux\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Semux API
 *
 * Semux is an experimental high-performance blockchain platform that powers decentralized application.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Semux\Client;

/**
 * PeerTypeTest Class Doc Comment
 *
 * @category Class 
*/
// * @description PeerType
/**
 * @package     Semux\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PeerTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PeerType"
     */
    public function testPeerType()
    {
    }

    /**
     * Test attribute "ip"
     */
    public function testPropertyIp()
    {
    }

    /**
     * Test attribute "port"
     */
    public function testPropertyPort()
    {
    }

    /**
     * Test attribute "networkVersion"
     */
    public function testPropertyNetworkVersion()
    {
    }

    /**
     * Test attribute "clientId"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "peerId"
     */
    public function testPropertyPeerId()
    {
    }

    /**
     * Test attribute "latestBlockNumber"
     */
    public function testPropertyLatestBlockNumber()
    {
    }

    /**
     * Test attribute "latency"
     */
    public function testPropertyLatency()
    {
    }

    /**
     * Test attribute "capabilities"
     */
    public function testPropertyCapabilities()
    {
    }
}
