<?php
/**
 * PeerType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Semux\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Semux API
 *
 * Semux is an experimental high-performance blockchain platform that powers decentralized application.
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Semux\Client\Model;

use \ArrayAccess;
use \Semux\Client\ObjectSerializer;

/**
 * PeerType Class Doc Comment
 *
 * @category Class
 * @package  Semux\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PeerType implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PeerType';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'ip' => 'string',
        'port' => 'int',
        'networkVersion' => 'int',
        'clientId' => 'string',
        'peerId' => 'string',
        'latestBlockNumber' => 'string',
        'latency' => 'string',
        'capabilities' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'ip' => null,
        'port' => 'int32',
        'networkVersion' => 'int32',
        'clientId' => null,
        'peerId' => null,
        'latestBlockNumber' => 'int64',
        'latency' => 'int64',
        'capabilities' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ip' => 'ip',
        'port' => 'port',
        'networkVersion' => 'networkVersion',
        'clientId' => 'clientId',
        'peerId' => 'peerId',
        'latestBlockNumber' => 'latestBlockNumber',
        'latency' => 'latency',
        'capabilities' => 'capabilities'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ip' => 'setIp',
        'port' => 'setPort',
        'networkVersion' => 'setNetworkVersion',
        'clientId' => 'setClientId',
        'peerId' => 'setPeerId',
        'latestBlockNumber' => 'setLatestBlockNumber',
        'latency' => 'setLatency',
        'capabilities' => 'setCapabilities'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ip' => 'getIp',
        'port' => 'getPort',
        'networkVersion' => 'getNetworkVersion',
        'clientId' => 'getClientId',
        'peerId' => 'getPeerId',
        'latestBlockNumber' => 'getLatestBlockNumber',
        'latency' => 'getLatency',
        'capabilities' => 'getCapabilities'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['ip'] = isset($data['ip']) ? $data['ip'] : null;
        $this->container['port'] = isset($data['port']) ? $data['port'] : null;
        $this->container['networkVersion'] = isset($data['networkVersion']) ? $data['networkVersion'] : null;
        $this->container['clientId'] = isset($data['clientId']) ? $data['clientId'] : null;
        $this->container['peerId'] = isset($data['peerId']) ? $data['peerId'] : null;
        $this->container['latestBlockNumber'] = isset($data['latestBlockNumber']) ? $data['latestBlockNumber'] : null;
        $this->container['latency'] = isset($data['latency']) ? $data['latency'] : null;
        $this->container['capabilities'] = isset($data['capabilities']) ? $data['capabilities'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['ip']) && !preg_match("/^(\\d{1,3}\\.){3}\\d{1,3}$/", $this->container['ip'])) {
            $invalidProperties[] = "invalid value for 'ip', must be conform to the pattern /^(\\d{1,3}\\.){3}\\d{1,3}$/.";
        }

        if (!is_null($this->container['latestBlockNumber']) && !preg_match("/^\\d+$/", $this->container['latestBlockNumber'])) {
            $invalidProperties[] = "invalid value for 'latestBlockNumber', must be conform to the pattern /^\\d+$/.";
        }

        if (!is_null($this->container['latency']) && !preg_match("/^\\d+$/", $this->container['latency'])) {
            $invalidProperties[] = "invalid value for 'latency', must be conform to the pattern /^\\d+$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if (!preg_match("/^(\\d{1,3}\\.){3}\\d{1,3}$/", $this->container['ip'])) {
            return false;
        }
        if (!preg_match("/^\\d+$/", $this->container['latestBlockNumber'])) {
            return false;
        }
        if (!preg_match("/^\\d+$/", $this->container['latency'])) {
            return false;
        }
        return true;
    }


    /**
     * Gets ip
     *
     * @return string
     */
    public function getIp()
    {
        return $this->container['ip'];
    }

    /**
     * Sets ip
     *
     * @param string $ip ip
     *
     * @return $this
     */
    public function setIp($ip)
    {

        if (!is_null($ip) && (!preg_match("/^(\\d{1,3}\\.){3}\\d{1,3}$/", $ip))) {
            throw new \InvalidArgumentException("invalid value for $ip when calling PeerType., must conform to the pattern /^(\\d{1,3}\\.){3}\\d{1,3}$/.");
        }

        $this->container['ip'] = $ip;

        return $this;
    }

    /**
     * Gets port
     *
     * @return int
     */
    public function getPort()
    {
        return $this->container['port'];
    }

    /**
     * Sets port
     *
     * @param int $port port
     *
     * @return $this
     */
    public function setPort($port)
    {
        $this->container['port'] = $port;

        return $this;
    }

    /**
     * Gets networkVersion
     *
     * @return int
     */
    public function getNetworkVersion()
    {
        return $this->container['networkVersion'];
    }

    /**
     * Sets networkVersion
     *
     * @param int $networkVersion networkVersion
     *
     * @return $this
     */
    public function setNetworkVersion($networkVersion)
    {
        $this->container['networkVersion'] = $networkVersion;

        return $this;
    }

    /**
     * Gets clientId
     *
     * @return string
     */
    public function getClientId()
    {
        return $this->container['clientId'];
    }

    /**
     * Sets clientId
     *
     * @param string $clientId clientId
     *
     * @return $this
     */
    public function setClientId($clientId)
    {
        $this->container['clientId'] = $clientId;

        return $this;
    }

    /**
     * Gets peerId
     *
     * @return string
     */
    public function getPeerId()
    {
        return $this->container['peerId'];
    }

    /**
     * Sets peerId
     *
     * @param string $peerId peerId
     *
     * @return $this
     */
    public function setPeerId($peerId)
    {
        $this->container['peerId'] = $peerId;

        return $this;
    }

    /**
     * Gets latestBlockNumber
     *
     * @return string
     */
    public function getLatestBlockNumber()
    {
        return $this->container['latestBlockNumber'];
    }

    /**
     * Sets latestBlockNumber
     *
     * @param string $latestBlockNumber latestBlockNumber
     *
     * @return $this
     */
    public function setLatestBlockNumber($latestBlockNumber)
    {

        if (!is_null($latestBlockNumber) && (!preg_match("/^\\d+$/", $latestBlockNumber))) {
            throw new \InvalidArgumentException("invalid value for $latestBlockNumber when calling PeerType., must conform to the pattern /^\\d+$/.");
        }

        $this->container['latestBlockNumber'] = $latestBlockNumber;

        return $this;
    }

    /**
     * Gets latency
     *
     * @return string
     */
    public function getLatency()
    {
        return $this->container['latency'];
    }

    /**
     * Sets latency
     *
     * @param string $latency latency
     *
     * @return $this
     */
    public function setLatency($latency)
    {

        if (!is_null($latency) && (!preg_match("/^\\d+$/", $latency))) {
            throw new \InvalidArgumentException("invalid value for $latency when calling PeerType., must conform to the pattern /^\\d+$/.");
        }

        $this->container['latency'] = $latency;

        return $this;
    }

    /**
     * Gets capabilities
     *
     * @return string[]
     */
    public function getCapabilities()
    {
        return $this->container['capabilities'];
    }

    /**
     * Sets capabilities
     *
     * @param string[] $capabilities capabilities
     *
     * @return $this
     */
    public function setCapabilities($capabilities)
    {
        $this->container['capabilities'] = $capabilities;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


